### ISSUE TITLE
subtitles extension gets confused by speaker view

### ISSUE THREAD

**Issue by mmbcorley** [parmsam/quarto-subtitles#2]
This extension works really well until I press 's' for speaker view, after which subtitles are shown on the upcoming slide in speaker view and the main view freezes.  Is there some way to anchor the subtitles to the main view to prevent this happening?  Many thanks

**Comment by parmsam** [comment]
Thanks for raising this issue! Unfortunately, this seems to be due to how speaker view is implemented in revealJS. Currently, many Quarto revealJS extensions do not work in speaker mode as expected. For example, the built-in chalkboard feature doesn't mirror speaker view annotations.

See here:
- https://github.com/quarto-dev/quarto-cli/issues/4987
- https://github.com/quarto-dev/quarto-cli/issues/2139
- https://github.com/hakimel/reveal.js/issues/2561

Leaving this issue open to see if I can keep the subtitles contained in the main view in a future release.

**Comment by parmsam** [comment]
This should be fixed in the latest release. Thanks! 

https://github.com/parmsam/quarto-subtitles/releases/tag/v1.1.0

**Comment by mmbcorley** [comment]
Fantastic. Many thanks
